import http from 'node:http';
import https from 'node:https';
import { Transform } from 'node:stream';
import { validateTarget, safeRequestHeaders, HOP_BY_HOP, framingDenied } from './security.js';
import { getProxySession, cookieHeader, storeSetCookies } from './cookies.js';
import { rewriteHtml, rewriteCss, rewriteJs, proxyPath } from './rewrite.js';
function decodeTarget(encoded){try{return Buffer.from(encoded,'base64url').toString('utf8')}catch{return''}}
function contentType(headers){return String(headers['content-type']||'').toLowerCase()}const isHtml=ct=>ct.includes('text/html')||ct.includes('application/xhtml+xml'),isCss=ct=>ct.includes('text/css'),isJs=ct=>ct.includes('javascript')||ct.includes('ecmascript');
function cleanResponseHeaders(headers,{rewritten=false}={}){const out={};for(const[k,v]of Object.entries(headers)){const key=k.toLowerCase();if(HOP_BY_HOP.has(key)||key==='set-cookie'||key==='location')continue;if(rewritten&&['content-length','content-encoding','etag','last-modified','accept-ranges'].includes(key))continue;if(v!==undefined)out[key]=v;}return out;}
function setHeaders(res,headers){for(const[k,v]of Object.entries(headers)){if(v!==undefined)try{res.setHeader(k,v)}catch{}}}
function compatibilityHtml(target,reason){return `<!doctype html><html><head><meta charset="utf-8"><title>FigureOS Compatibility</title><style>html,body{height:100%;margin:0;background:#0b0b0e;color:#f5f5f7;font:14px Inter,system-ui,sans-serif}body{display:grid;place-items:center}.c{max-width:620px;margin:25px;padding:28px;border:1px solid #2a2a31;border-radius:22px;background:#121216}small{color:#777;letter-spacing:1.5px}h1{font-size:24px}p{color:#aaa;line-height:1.6}code{display:block;padding:12px;border-radius:10px;background:#060608;color:#bbb;overflow-wrap:anywhere}</style></head><body><main class="c"><small>FIGURE BROWSER / COMPATIBILITY</small><h1>This destination refuses embedded browsing.</h1><p>FigureOS preserved the upstream framing policy instead of stripping it. If you control this service, explicitly authorize your FigureOS origin in its framing/CSP configuration.</p><code>${escapeHtml(target.origin)}</code><p>${escapeHtml(reason)}</p></main></body></html>`}
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function readStream(stream,max){const chunks=[];let size=0;for await(const chunk of stream){size+=chunk.length;if(size>max){stream.destroy();throw error(502,'Upstream response exceeded configured size limit.')}chunks.push(chunk)}return Buffer.concat(chunks)}
async function readBody(req,max){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>max)throw error(413,'Upload exceeds configured size limit.');chunks.push(c)}return Buffer.concat(chunks)}
function requestUpstream(target,addresses,{method,headers,body,timeout}){return new Promise((resolve,reject)=>{const client=target.protocol==='https:'?https:http,row=addresses[0];const lookup=(hostname,opts,cb)=>opts?.all?cb(null,[row]):cb(null,row.address,row.family);const r=client.request(target,{method,headers,lookup,servername:target.hostname},resolve);r.on('error',reject);r.setTimeout(timeout,()=>r.destroy(error(504,'Upstream request timed out.')));if(body?.length)r.write(body);r.end();})}
export function createProxyGateway({allowedOrigins,publicOrigin,timeoutMs,maxResponseBytes,maxUploadBytes,validateTargetFn=validateTarget,requestUpstreamFn=requestUpstream}){return async function handleProxy(req,res,encoded){try{const raw=decodeTarget(encoded),{url:target,addresses}=await validateTargetFn(raw,allowedOrigins);const session=getProxySession(req,res,publicOrigin),headers=safeRequestHeaders(req.headers,target);headers['accept-encoding']='identity';const cookies=cookieHeader(session,target.href);if(cookies)headers.cookie=cookies;const body=['GET','HEAD'].includes(req.method)?Buffer.alloc(0):await readBody(req,maxUploadBytes);if(body.length)headers['content-length']=String(body.length);const upstream=await requestUpstreamFn(target,addresses,{method:req.method,headers,body,timeout:timeoutMs});storeSetCookies(session,target.href,upstream.headers['set-cookie']||[]);const ct=contentType(upstream.headers),frame=framingDenied(upstream.headers,publicOrigin);
    if(isHtml(ct)&&frame.denied){upstream.destroy();const html=compatibilityHtml(target,frame.reason);res.statusCode=409;setHeaders(res,{'content-type':'text/html; charset=utf-8','cache-control':'no-store, private','surrogate-control':'no-store','x-content-type-options':'nosniff'});res.end(html);return;}
    if(upstream.statusCode>=300&&upstream.statusCode<400&&upstream.headers.location){const loc=new URL(upstream.headers.location,target.href),h=cleanResponseHeaders(upstream.headers);h.location=['http:','https:'].includes(loc.protocol)?proxyPath(loc.href):loc.href;h['cache-control']='no-store, private';h['surrogate-control']='no-store';res.statusCode=upstream.statusCode;setHeaders(res,h);upstream.pipe(res);return;}
    const rewrite=isHtml(ct)||isCss(ct)||isJs(ct),h=cleanResponseHeaders(upstream.headers,{rewritten:rewrite});h['cache-control']='no-store, private';h['surrogate-control']='no-store';h['x-content-type-options']=h['x-content-type-options']||'nosniff';h['x-figureos-proxy']='authorized-origin';res.statusCode=upstream.statusCode||502;setHeaders(res,h);if(req.method==='HEAD'){upstream.destroy();res.end();return;}
    if(rewrite){const buf=await readStream(upstream,maxResponseBytes);let text=buf.toString('utf8');if(isHtml(ct))text=rewriteHtml(text,target);else if(isCss(ct))text=rewriteCss(text,target.href);else text=rewriteJs(text,target.href);res.end(Buffer.from(text));return;}
    let seen=0;const limiter=new Transform({transform(chunk,enc,cb){seen+=chunk.length;if(seen>maxResponseBytes)return cb(error(502,'Upstream response exceeded configured size limit.'));cb(null,chunk)}});limiter.on('error',()=>{upstream.destroy();if(!res.headersSent){res.statusCode=502;res.end('Proxy response limit exceeded.')}else res.destroy()});upstream.pipe(limiter).pipe(res);
  }catch(err){const status=Number(err.statusCode)||502;if(!res.headersSent){res.statusCode=status;setHeaders(res,{'cache-control':'no-store','content-type':'application/json; charset=utf-8'});res.end(JSON.stringify({error:'proxy_error',message:sanitizeError(err,status)}))}else res.destroy()}}}
function sanitizeError(err,status){if(status===403||status===400||status===413)return err.message;if(status===504)return'Authorized destination timed out.';return'Authorized destination could not be loaded.'}
function error(statusCode,message){return Object.assign(new Error(message),{statusCode})}
