import net from 'node:net';
import tls from 'node:tls';
import { validateTarget } from './security.js';
import { getProxySessionFromCookie, cookieHeader, storeSetCookies } from './cookies.js';
function decodeTarget(encoded){try{return Buffer.from(encoded,'base64url').toString('utf8')}catch{return''}}
function reject(socket,status=400,message='Bad Request'){const body=message;try{socket.write(`HTTP/1.1 ${status} ${message}\r\nConnection: close\r\nContent-Type: text/plain\r\nContent-Length: ${Buffer.byteLength(body)}\r\n\r\n${body}`)}finally{socket.destroy()}}
export function attachWebSocketProxy(server,{allowedOrigins,publicOrigin,timeoutMs,originSecret='',maxBytes=512*1024*1024}){let open=0;const perIp=new Map();server.on('upgrade',async(req,client,head)=>{let pathname;try{pathname=new URL(req.url,publicOrigin||'http://localhost').pathname}catch{return reject(client)}if(!pathname.startsWith('/socket/'))return reject(client,404,'Not Found');if(originSecret&&!secretMatch(req.headers['x-figureos-origin-secret'],originSecret))return reject(client,403,'Forbidden');if(publicOrigin&&req.headers.origin&&req.headers.origin!==publicOrigin)return reject(client,403,'Forbidden');const ip=client.remoteAddress||'unknown';if(open>=200||(perIp.get(ip)||0)>=30)return reject(client,429,'Too Many Connections');try{const raw=decodeTarget(pathname.slice(8)),{url:target,addresses}=await validateTarget(raw,allowedOrigins,['ws:','wss:']);open++;perIp.set(ip,(perIp.get(ip)||0)+1);client.once('close',()=>{open=Math.max(0,open-1);perIp.set(ip,Math.max(0,(perIp.get(ip)||1)-1))});await bridge(req,client,head,target,addresses[0],{publicOrigin,timeoutMs,maxBytes})}catch(err){reject(client,Number(err.statusCode)||502,Number(err.statusCode)===403?'Forbidden':'Bad Gateway')}})}
async function bridge(req,client,head,target,address,{publicOrigin,timeoutMs,maxBytes}){const session=getProxySessionFromCookie(req.headers.cookie||'',publicOrigin),cookieUrl=new URL(target.href);cookieUrl.protocol=target.protocol==='wss:'?'https:':'http:';const cookies=cookieHeader(session,cookieUrl.href);const port=Number(target.port)||(target.protocol==='wss:'?443:80);const upstream=target.protocol==='wss:'?tls.connect({host:address.address,port,servername:target.hostname,rejectUnauthorized:true}):net.connect({host:address.address,port});const timer=setTimeout(()=>{upstream.destroy();client.destroy()},timeoutMs);await onceConnect(upstream);clearTimeout(timer);const lines=[`GET ${target.pathname}${target.search} HTTP/1.1`,`Host: ${target.host}`,'Upgrade: websocket','Connection: Upgrade'];for(const h of ['sec-websocket-key','sec-websocket-version','sec-websocket-protocol','sec-websocket-extensions','user-agent'])if(req.headers[h])lines.push(`${canonical(h)}: ${req.headers[h]}`);lines.push(`Origin: ${cookieUrl.origin}`);if(cookies)lines.push(`Cookie: ${cookies}`);lines.push('\r\n');upstream.write(lines.join('\r\n'));let buffer=Buffer.alloc(0),ready=false,clientBytes=0,upstreamBytes=0;const onData=chunk=>{if(ready)return;buffer=Buffer.concat([buffer,chunk]);const idx=buffer.indexOf('\r\n\r\n');if(idx<0){if(buffer.length>64*1024){upstream.destroy();client.destroy()}return;}upstream.off('data',onData);const headerText=buffer.slice(0,idx).toString('latin1'),rest=buffer.slice(idx+4),parsed=parseHandshake(headerText);if(parsed.status!==101){client.write(Buffer.from(headerText+'\r\n\r\n','latin1'));if(rest.length)client.write(rest);client.end();upstream.end();return;}storeSetCookies(session,cookieUrl.href,parsed.setCookies);const responseLines=[parsed.statusLine,...parsed.headers.filter(([k])=>k.toLowerCase()!=='set-cookie').map(([k,v])=>`${k}: ${v}`),'',''];client.write(responseLines.join('\r\n'));if(rest.length)client.write(rest);if(head?.length)upstream.write(head);ready=true;upstream.on('data',d=>{upstreamBytes+=d.length;if(upstreamBytes>maxBytes){upstream.destroy();client.destroy();return}if(!client.destroyed)client.write(d)});client.on('data',d=>{clientBytes+=d.length;if(clientBytes>maxBytes){upstream.destroy();client.destroy();return}if(!upstream.destroyed)upstream.write(d)});client.on('end',()=>upstream.end());client.on('error',()=>upstream.destroy());upstream.on('end',()=>client.end());upstream.on('error',()=>client.destroy());};upstream.on('data',onData)}
function onceConnect(socket){return new Promise((resolve,reject)=>{const event=socket.encrypted?'secureConnect':'connect';socket.once(event,resolve);socket.once('error',reject)})}
function parseHandshake(text){const lines=text.split('\r\n'),statusLine=lines.shift()||'',status=Number(statusLine.split(' ')[1]||0),headers=[],setCookies=[];for(const line of lines){const i=line.indexOf(':');if(i<1)continue;const k=line.slice(0,i),v=line.slice(i+1).trim();headers.push([k,v]);if(k.toLowerCase()==='set-cookie')setCookies.push(v)}return{statusLine,status,headers,setCookies}}
function canonical(h){return h.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join('-')}

function secretMatch(got,expected){const a=Buffer.from(String(got||'')),b=Buffer.from(String(expected||''));return a.length===b.length&&a.length>0&&a.equals(b)}
