import test from 'node:test';import assert from 'node:assert/strict';
import { createServer } from '../server/server.js';
let server,base;
test.before(async()=>{server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const a=server.address();base=`http://127.0.0.1:${a.port}`;});
test.after(async()=>{await new Promise(r=>server.close(r));});
test('home, health, manifest, and Figure app load',async()=>{for(const [path,needle] of [['/','FigureOS'],['/api/health','figureos-origin'],['/manifest.webmanifest','FigureOS'],['/figure/','G_DATA']]){const r=await fetch(base+path);assert.equal(r.ok,true,path);assert.match(await r.text(),new RegExp(needle));}});
test('browser proxy rejects unapproved destinations',async()=>{const enc=Buffer.from('https://example.com/').toString('base64url');const r=await fetch(`${base}/proxy/${enc}`);assert.equal(r.status,403);const j=await r.json();assert.match(j.message,/PROXY_ALLOWED_ORIGINS/);});
test('CSRF flow protects assistant API',async()=>{const c=await fetch(base+'/api/csrf');const {token}=await c.json(),cookie=c.headers.get('set-cookie').split(';')[0];let r=await fetch(base+'/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:'{"message":"hello"}'});assert.equal(r.status,403);r=await fetch(base+'/api/assistant',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':token,'cookie':cookie},body:'{"message":"hello"}'});assert.equal(r.status,501);});
test('local media supports byte ranges',async()=>{const r=await fetch(base+'/figure/Tutorial.mp4',{headers:{range:'bytes=0-99'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,100);assert.match(r.headers.get('content-range'),/^bytes 0-99\//);});
test('service worker excludes authenticated proxy/API routes from caching',async()=>{const r=await fetch(base+'/sw.js');const s=await r.text();assert.match(s,/pathname\.startsWith\('\/proxy\/'\)/);assert.match(s,/pathname\.startsWith\('\/api\/'\)/);});
