import crypto from 'node:crypto';
const sessions=new Map(),TTL=12*60*60*1000,MAX_COOKIES=100;
function parseHeader(header=''){return Object.fromEntries(header.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
function secure(publicOrigin){try{return new URL(publicOrigin).protocol==='https:'}catch{return false}}
function sessionName(publicOrigin){return secure(publicOrigin)?'__Host-figure_proxy_sid':'figure_proxy_sid';}
export function getProxySession(req,res,publicOrigin=''){const name=sessionName(publicOrigin),cookies=parseHeader(req.headers.cookie||'');let sid=cookies[name];if(!sid||!/^[A-Za-z0-9_-]{30,80}$/.test(sid))sid=crypto.randomBytes(32).toString('base64url');let entry=sessions.get(sid);if(!entry){entry={cookies:[],touched:Date.now()};sessions.set(sid,entry);}entry.touched=Date.now();res.setHeader('Set-Cookie',`${name}=${sid}; Path=/; HttpOnly; SameSite=Strict${secure(publicOrigin)?'; Secure':''}`);cleanup();return entry;}
export function getProxySessionFromCookie(header='',publicOrigin=''){const sid=parseHeader(header)[sessionName(publicOrigin)];return sid?sessions.get(sid)||null:null;}
export function cookieHeader(session,url){if(!session)return'';const u=new URL(url),now=Date.now();session.cookies=session.cookies.filter(c=>!c.expires||c.expires>now);return session.cookies.filter(c=>c.host===u.hostname&&u.pathname.startsWith(c.path)&&(!c.secure||['https:','wss:'].includes(u.protocol))).map(c=>`${c.name}=${c.value}`).join('; ');}
export function storeSetCookies(session,url,setCookies=[]){if(!session)return;const u=new URL(url);for(const raw of(Array.isArray(setCookies)?setCookies:[setCookies])){if(!raw||raw.length>8192)continue;const parts=raw.split(';').map(x=>x.trim()),nv=parts.shift(),i=nv.indexOf('=');if(i<=0)continue;const c={name:nv.slice(0,i),value:nv.slice(i+1),host:u.hostname,path:defaultPath(u.pathname),secure:false,expires:0};if(c.value.length>4096)continue;let domainOk=true;for(const attr of parts){const j=attr.indexOf('='),k=(j<0?attr:attr.slice(0,j)).toLowerCase(),v=j<0?'':attr.slice(j+1);if(k==='domain'){const d=v.replace(/^\./,'').toLowerCase();if(d!==u.hostname.toLowerCase())domainOk=false;}if(k==='path'&&v.startsWith('/'))c.path=v;if(k==='secure')c.secure=true;if(k==='max-age'){const n=Number(v);if(Number.isFinite(n))c.expires=Date.now()+n*1000;}if(k==='expires'){const t=Date.parse(v);if(Number.isFinite(t))c.expires=t;}}if(!domainOk)continue;session.cookies=session.cookies.filter(x=>!(x.name===c.name&&x.host===c.host&&x.path===c.path));if(!c.expires||c.expires>Date.now())session.cookies.push(c);if(session.cookies.length>MAX_COOKIES)session.cookies.splice(0,session.cookies.length-MAX_COOKIES);}}
function defaultPath(p){if(!p.startsWith('/')||p==='/')return'/';const i=p.lastIndexOf('/');return i<=0?'/':p.slice(0,i+1);}
function cleanup(){const now=Date.now();for(const[k,v]of sessions)if(now-v.touched>TTL)sessions.delete(k);}
