import dns from 'node:dns/promises';
import net from 'node:net';
export const HOP_BY_HOP=new Set(['connection','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','upgrade']);
export function parseAllowedOrigins(value=''){return new Set(value.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{try{return new URL(x).origin}catch{return''}}).filter(Boolean));}
function ipv4Parts(ip){const p=ip.split('.').map(Number);return p.length===4&&p.every(n=>Number.isInteger(n)&&n>=0&&n<=255)?p:null;}
export function isPrivateAddress(address){
  const family=net.isIP(address);if(!family)return true;
  if(family===4){const p=ipv4Parts(address);if(!p)return true;const [a,b,c]=p;return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===192&&b===0)||(a===192&&b===0&&c===2)||(a===198&&(b===18||b===19))||(a===198&&b===51&&c===100)||(a===203&&b===0&&c===113)||a>=224;}
  const ip=address.toLowerCase();if(ip==='::'||ip==='::1')return true;const mapped=ip.match(/::ffff:(\d+\.\d+\.\d+\.\d+)$/);if(mapped)return isPrivateAddress(mapped[1]);return ip.startsWith('fc')||ip.startsWith('fd')||/^fe[89ab]/.test(ip)||ip.startsWith('ff')||ip.startsWith('2001:db8:')||ip.startsWith('2001:0:')||ip.startsWith('2001:10:')||ip.startsWith('2001:20:');
}
export function normalizeHttpOrigin(url){const u=new URL(url);if(u.protocol==='ws:')u.protocol='http:';if(u.protocol==='wss:')u.protocol='https:';return u.origin;}
export function assertTargetShape(raw,allowedOrigins,protocols=['http:','https:']){let u;try{u=new URL(raw)}catch{throw error(400,'Invalid destination URL.')}if(!protocols.includes(u.protocol))throw error(400,'Protocol is not allowed.');if(u.username||u.password)throw error(400,'Credentials in destination URLs are not allowed.');const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.localhost'))throw error(403,'Local destinations are blocked.');if(net.isIP(host)&&isPrivateAddress(host))throw error(403,'Private network destinations are blocked.');if(!allowedOrigins.has(normalizeHttpOrigin(u.href)))throw error(403,'Destination origin is not on PROXY_ALLOWED_ORIGINS.');return u;}
export async function resolvePublicTarget(url){if(net.isIP(url.hostname)){if(isPrivateAddress(url.hostname))throw error(403,'Private network destinations are blocked.');return[{address:url.hostname,family:net.isIP(url.hostname)}];}let rows;try{rows=await dns.lookup(url.hostname,{all:true,verbatim:true})}catch{throw error(502,'Destination DNS lookup failed.')}if(!rows.length||rows.some(r=>isPrivateAddress(r.address)))throw error(403,'Destination resolved to a private or unsafe address.');return rows;}
export async function validateTarget(raw,allowedOrigins,protocols=['http:','https:']){const url=assertTargetShape(raw,allowedOrigins,protocols);const addresses=await resolvePublicTarget(url);return{url,addresses};}
export function safeRequestHeaders(headers,target){const out={};for(const[k,v]of Object.entries(headers)){const key=k.toLowerCase();if(HOP_BY_HOP.has(key)||['host','cookie','content-length'].includes(key)||v===undefined)continue;out[key]=v;}delete out['accept-encoding'];if(out.origin)out.origin=target.origin;if(out.referer){try{const r=new URL(out.referer);out.referer=new URL(r.pathname+r.search+r.hash,target.origin).href}catch{delete out.referer}}return out;}
export function framingDenied(headers,publicOrigin=''){const xfo=String(headers['x-frame-options']||'').trim().toLowerCase();if(xfo==='deny'||xfo==='sameorigin')return{denied:true,reason:`Upstream sent X-Frame-Options: ${headers['x-frame-options']}.`};if(xfo.startsWith('allow-from')){const allowed=xfo.slice(10).trim();if(!publicOrigin||allowed!==publicOrigin.toLowerCase())return{denied:true,reason:'Upstream X-Frame-Options does not authorize the FigureOS origin.'};}const csp=String(headers['content-security-policy']||'');const m=csp.match(/(?:^|;)\s*frame-ancestors\s+([^;]+)/i);if(m){const tokens=m[1].trim().split(/\s+/);if(tokens.includes("'none'"))return{denied:true,reason:"Upstream CSP frame-ancestors is 'none'."};if(tokens.includes('*'))return{denied:false};const po=publicOrigin.toLowerCase();const explicit=po&&tokens.some(t=>t.toLowerCase()===po);if(tokens.includes("'self'")&&!explicit)return{denied:true,reason:"Upstream CSP frame-ancestors only permits 'self'."};if(!explicit&&!tokens.includes('https:')&&!tokens.includes('http:'))return{denied:true,reason:'Upstream CSP frame-ancestors does not authorize the FigureOS origin.'};}return{denied:false};}
function error(statusCode,message){return Object.assign(new Error(message),{statusCode});}
