import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import http from 'node:http';
import { fileURLToPath } from 'node:url';
import { parseAllowedOrigins } from './proxy/security.js';
import { createProxyGateway } from './proxy/gateway.js';
import { attachWebSocketProxy } from './proxy/websocket.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),ROOT=path.resolve(__dirname,'..');loadEnv(path.join(ROOT,'.env'));
const PORT=num(process.env.PORT,3000),PUBLIC_ORIGIN=process.env.PUBLIC_ORIGIN||`http://localhost:${PORT}`,ORIGIN_SECRET=process.env.BUNNY_ORIGIN_SECRET||'',ALLOWED=parseAllowedOrigins(process.env.PROXY_ALLOWED_ORIGINS||''),TIMEOUT=num(process.env.PROXY_REQUEST_TIMEOUT_MS,15000),MAX_RESPONSE=num(process.env.PROXY_MAX_RESPONSE_BYTES,50*1024*1024),MAX_UPLOAD=num(process.env.PROXY_MAX_UPLOAD_BYTES,10*1024*1024),PROXY_RATE=num(process.env.PROXY_RATE_LIMIT_PER_MINUTE,120);
const proxyGateway=createProxyGateway({allowedOrigins:ALLOWED,publicOrigin:PUBLIC_ORIGIN,timeoutMs:TIMEOUT,maxResponseBytes:MAX_RESPONSE,maxUploadBytes:MAX_UPLOAD});
const proxyHits=new Map(),apiHits=new Map();
export function createServer(){const server=http.createServer(handle);attachWebSocketProxy(server,{allowedOrigins:ALLOWED,publicOrigin:PUBLIC_ORIGIN,timeoutMs:TIMEOUT,originSecret:ORIGIN_SECRET});return server;}
async function handle(req,res){try{const url=new URL(req.url,PUBLIC_ORIGIN);if(ORIGIN_SECRET&&!secretMatch(req.headers['x-figureos-origin-secret'],ORIGIN_SECRET))return json(res,403,{error:'origin_auth_failed'});if(url.pathname.startsWith('/proxy/')){if(!rate(proxyHits,clientKey(req),PROXY_RATE,60_000))return json(res,429,{error:'rate_limited',message:'Too many proxy requests.'},{'cache-control':'no-store'});return proxyGateway(req,res,url.pathname.slice('/proxy/'.length));}
  securityHeaders(res,url.pathname);
  if(url.pathname.startsWith('/api/')){res.setHeader('Cache-Control','no-store');if(!rate(apiHits,clientKey(req),180,60_000))return json(res,429,{error:'rate_limited'});if(url.pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,service:'figureos-origin',time:new Date().toISOString()});if(url.pathname==='/api/config'&&req.method==='GET')return json(res,200,{proxyEnabled:ALLOWED.size>0,proxyAllowedOrigins:[...ALLOWED],browserSearchTemplate:process.env.BROWSER_SEARCH_TEMPLATE||''});if(url.pathname==='/api/csrf'&&req.method==='GET'){const token=crypto.randomBytes(24).toString('base64url');setCsrfCookie(res,token);return json(res,200,{token});}if(url.pathname==='/api/assistant'&&req.method==='POST')return assistant(req,res);return json(res,404,{error:'not_found'});}
  if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'method_not_allowed'});
  if(url.pathname==='/')return serveFile(req,res,path.join(ROOT,'index.html'),{cache:'no-cache'});
  if(url.pathname==='/manifest.webmanifest')return serveFile(req,res,path.join(ROOT,'public','manifest.webmanifest'),{cache:'no-cache'});
  if(url.pathname==='/sw.js')return serveFile(req,res,path.join(ROOT,'public','sw.js'),{cache:'no-cache'});
  if(url.pathname==='/offline.html')return serveFile(req,res,path.join(ROOT,'public','offline.html'),{cache:'no-cache'});
  if(url.pathname.startsWith('/src/')){const p=safeJoin(path.join(ROOT,'src'),url.pathname.slice(5));if(p)return serveFile(req,res,p,{cache:'public, max-age=3600'});}
  if(url.pathname.startsWith('/icons/')){const p=safeJoin(path.join(ROOT,'public','icons'),url.pathname.slice(7));if(p)return serveFile(req,res,p,{cache:'public, max-age=604800'});}
  if(url.pathname==='/figure'||url.pathname==='/figure/')return serveFile(req,res,path.join(ROOT,'figure','index.html'),{cache:'no-cache'});
  if(url.pathname.startsWith('/figure/')){const p=safeJoin(path.join(ROOT,'figure'),url.pathname.slice(8));if(p)return serveFile(req,res,p,{cache:p.endsWith('.html')?'no-cache':'public, max-age=600'});}
  if(acceptsHtml(req))return serveFile(req,res,path.join(ROOT,'index.html'),{cache:'no-cache'});return json(res,404,{error:'not_found'});
}catch{return json(res,500,{error:'server_error'});}}
async function assistant(req,res){if(req.headers.origin&&req.headers.origin!==PUBLIC_ORIGIN)return json(res,403,{message:'Origin rejected.'});const cookies=parseCookies(req.headers.cookie||''),header=String(req.headers['x-csrf-token']||''),cookie=cookies.figure_csrf||'';if(!cookie||!header||cookie.length!==header.length||!crypto.timingSafeEqual(Buffer.from(cookie),Buffer.from(header)))return json(res,403,{message:'CSRF validation failed.'});let body;try{body=JSON.parse((await readBody(req,64*1024)).toString('utf8')||'{}')}catch{return json(res,400,{message:'Invalid JSON.'})}const message=String(body.message||'').trim().slice(0,2000);if(!message)return json(res,400,{message:'Message is required.'});const endpoint=process.env.ASSISTANT_PROVIDER_URL;if(!endpoint)return json(res,501,{message:'No external assistant provider is configured. Local CIRI commands are still available.'});try{const u=new URL(endpoint);if(!['https:','http:'].includes(u.protocol))throw new Error();const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),TIMEOUT),headers={'content-type':'application/json'};if(process.env.ASSISTANT_PROVIDER_TOKEN)headers.authorization=`Bearer ${process.env.ASSISTANT_PROVIDER_TOKEN}`;const r=await fetch(u,{method:'POST',headers,body:JSON.stringify({message}),signal:ctrl.signal});clearTimeout(timer);const data=await r.json().catch(()=>({}));if(!r.ok)return json(res,502,{message:'Assistant provider returned an error.'});return json(res,200,{message:String(data.message||data.output||data.response||'Assistant provider returned no message.').slice(0,8000)});}catch{return json(res,502,{message:'Assistant provider is unavailable.'})}}
async function serveFile(req,res,file,{cache='public, max-age=600'}={}){let st;try{st=await fsp.stat(file);if(!st.isFile())throw new Error()}catch{return json(res,404,{error:'not_found'})}const type=mime(file);res.setHeader('Content-Type',type);res.setHeader('Cache-Control',cache);res.setHeader('Accept-Ranges','bytes');const range=req.headers.range;if(range){const m=String(range).match(/^bytes=(\d*)-(\d*)$/);if(m){let start=m[1]?Number(m[1]):0,end=m[2]?Number(m[2]):st.size-1;if(!m[1]&&m[2]){const suffix=Number(m[2]);start=Math.max(0,st.size-suffix);end=st.size-1}if(start<=end&&end<st.size){res.statusCode=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${st.size}`);res.setHeader('Content-Length',String(end-start+1));if(req.method==='HEAD')return res.end();fs.createReadStream(file,{start,end}).pipe(res);return;}}res.statusCode=416;res.setHeader('Content-Range',`bytes */${st.size}`);return res.end()}res.statusCode=200;res.setHeader('Content-Length',String(st.size));if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res);}
function securityHeaders(res,pathname){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('X-Frame-Options','SAMEORIGIN');if(!pathname.startsWith('/api/'))res.setHeader('Content-Security-Policy',"default-src 'self' https: data: blob:; img-src 'self' https: data: blob:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; font-src 'self' https: data:; media-src 'self' https: blob: data:; frame-src 'self' https:; connect-src 'self' https: wss: ws:; worker-src 'self' blob:; manifest-src 'self'");}
function json(res,status,data,headers={}){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');for(const[k,v]of Object.entries(headers))res.setHeader(k,v);res.end(JSON.stringify(data));}
async function readBody(req,max){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>max)throw new Error('too large');chunks.push(c)}return Buffer.concat(chunks)}
function safeJoin(base,relative){const p=path.resolve(base,'.'+path.sep+relative.replace(/^\/+/,''));return p===base||p.startsWith(base+path.sep)?p:null;}
function acceptsHtml(req){return String(req.headers.accept||'').includes('text/html');}
function mime(file){const ext=path.extname(file).toLowerCase();return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.mp3':'audio/mpeg','.mp4':'video/mp4','.woff':'font/woff','.woff2':'font/woff2'}[ext]||'application/octet-stream')}
function parseCookies(header=''){return Object.fromEntries(header.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
function setCsrfCookie(res,token){let secure=false;try{secure=new URL(PUBLIC_ORIGIN).protocol==='https:'}catch{}res.setHeader('Set-Cookie',`figure_csrf=${token}; Path=/; HttpOnly; SameSite=Strict${secure?'; Secure':''}`)}
function rate(map,key,limit,windowMs){const now=Date.now(),v=map.get(key);if(!v||now-v.start>windowMs){map.set(key,{start:now,count:1});return true}v.count++;return v.count<=limit}
function clientKey(req){return req.socket.remoteAddress||'unknown'}
function secretMatch(got,expected){const a=Buffer.from(String(got||'')),b=Buffer.from(String(expected||''));return a.length===b.length&&a.length>0&&crypto.timingSafeEqual(a,b)}
function num(v,f){const n=Number(v);return Number.isFinite(n)&&n>0?n:f}
function loadEnv(file){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith('#'))continue;const i=t.indexOf('=');if(i<1)continue;const k=t.slice(0,i).trim();if(process.env[k]!==undefined)continue;let v=t.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[k]=v}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){createServer().listen(PORT,()=>{console.log(`FigureOS origin listening on ${PUBLIC_ORIGIN}`);console.log(`Proxy allowlist entries: ${ALLOWED.size}`)})}
