let audio=null,currentUrl='';
export function renderMusicApp(root){
  root.innerHTML=`<div class="music-app"><div><div class="music-player-art">♪</div><input id="music-file" type="file" accept="audio/*" style="margin-top:14px;width:100%"></div><div class="music-controls"><small style="letter-spacing:1.5px;color:#777">LOCAL AUDIO</small><h2 id="music-title">Nothing selected</h2><p id="music-meta">Choose an audio file. Playback stays on this device.</p><div class="music-control-row"><button id="music-toggle" disabled>▶</button><span id="music-time" style="font-size:10px;color:#888">0:00 / 0:00</span></div><input class="music-progress" id="music-progress" type="range" min="0" max="100" value="0"><label style="font-size:9px;color:#888;margin-top:15px">Volume <input id="music-volume" type="range" min="0" max="1" step="0.01" value="0.8"></label></div></div>`;
  const file=root.querySelector('#music-file'),toggle=root.querySelector('#music-toggle'),progress=root.querySelector('#music-progress'),volume=root.querySelector('#music-volume');
  file.onchange=()=>{const f=file.files?.[0];if(!f)return;if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(f);if(audio)audio.pause();audio=new Audio(currentUrl);audio.volume=.8;root.querySelector('#music-title').textContent=f.name;root.querySelector('#music-meta').textContent=`${(f.size/1024/1024).toFixed(1)} MB • ${f.type||'audio'}`;toggle.disabled=false;toggle.textContent='▶';syncHome(f.name,false);bindAudio(root,toggle,progress);};
  toggle.onclick=()=>{if(!audio)return;if(audio.paused)audio.play();else audio.pause();};progress.oninput=()=>{if(audio?.duration)audio.currentTime=(+progress.value/100)*audio.duration;};volume.oninput=()=>{if(audio)audio.volume=+volume.value;};
}
function bindAudio(root,toggle,progress){audio.ontimeupdate=()=>{const d=audio.duration||0;progress.value=d?String((audio.currentTime/d)*100):'0';root.querySelector('#music-time').textContent=`${fmt(audio.currentTime)} / ${fmt(d)}`;};audio.onplay=()=>{toggle.textContent='❚❚';syncHome(root.querySelector('#music-title').textContent,true)};audio.onpause=()=>{toggle.textContent='▶';syncHome(root.querySelector('#music-title').textContent,false)};audio.onended=audio.onpause;}
function fmt(s){if(!Number.isFinite(s))return'0:00';const m=Math.floor(s/60),x=Math.floor(s%60);return `${m}:${String(x).padStart(2,'0')}`;}
function syncHome(name,playing){const t=document.getElementById('music-home-title'),s=document.getElementById('music-home-subtitle'),b=document.getElementById('music-home-toggle');if(t)t.textContent=name;if(s)s.textContent=playing?'Playing local audio':'Paused';if(b){b.disabled=!audio;b.textContent=playing?'❚❚':'▶';b.onclick=()=>audio&&(audio.paused?audio.play():audio.pause());}}
