import { state, patchState } from '../state.js';
import { themes, applyTheme } from '../themes.js';
import { applyParticles } from '../particles.js';
const wallpapers={figure:'radial-gradient(circle at 75% 18%,rgba(var(--accent-rgb),.14),transparent 28%),linear-gradient(145deg,var(--bg),#020202 72%)',void:'radial-gradient(circle at 20% 20%,#17171d,transparent 35%),linear-gradient(160deg,#050506,#000)',aurora:'radial-gradient(circle at 75% 20%,rgba(0,210,255,.24),transparent 28%),radial-gradient(circle at 20% 85%,rgba(165,94,234,.2),transparent 30%),#030509',ember:'radial-gradient(circle at 75% 20%,rgba(255,70,40,.23),transparent 30%),linear-gradient(150deg,#110302,#020202)',ocean:'radial-gradient(circle at 72% 20%,rgba(10,189,227,.25),transparent 30%),linear-gradient(160deg,#020914,#010204)'};
export function applyWallpaper(id=state.wallpaper){const el=document.getElementById('wallpaper');const value=id==='custom'&&state.customWallpaper?`url("${state.customWallpaper.replace(/"/g,'')}")`:wallpapers[id]||wallpapers.figure;el.style.background=value;document.documentElement.style.setProperty('--lock-wallpaper',value);}
export function renderSettings(){const root=document.getElementById('settings-content');root.innerHTML=`
  <section class="settings-card wide"><h3>Themes</h3><p>These are the Figure theme families from the original project, applied across the whole WebOS.</p><div class="theme-grid">${Object.entries(themes).map(([id,t])=>`<button class="theme-swatch ${state.theme===id?'active':''}" data-theme="${id}" title="${t.name}" style="--swatch:${t.accent}"><span></span></button>`).join('')}</div></section>
  <section class="settings-card"><h3>Particles</h3><p>Global particles stay synchronized with the embedded Figure app.</p><div class="particle-grid">${[['none','○'],['snow','✣'],['rain','╱'],['stars','✦'],['cyber','⌁'],['matrix','⌘'],['bubbles','◌'],['fireflies','·'],['nexus','⌬']].map(([id,ic])=>`<button class="particle-option ${state.particles===id?'active':''}" data-particles="${id}"><span>${ic}</span><small>${id}</small></button>`).join('')}</div></section>
  <section class="settings-card"><h3>Wallpaper</h3><p>Choose a built-in cinematic wallpaper or an operator-controlled image URL.</p><div class="wallpaper-grid">${Object.keys(wallpapers).map(id=>`<button class="wallpaper-option ${state.wallpaper===id?'active':''}" data-wallpaper="${id}"><span>◫</span><small>${id}</small></button>`).join('')}<button class="wallpaper-option ${state.wallpaper==='custom'?'active':''}" data-wallpaper="custom"><span>＋</span><small>custom</small></button></div><div class="setting-row"><div><label>Custom image URL</label><small>Stored locally. Use HTTPS in production.</small></div><input id="custom-wallpaper" type="url" value="${escapeHtml(state.customWallpaper)}" placeholder="https://…"></div></section>
  <section class="settings-card"><h3>Browser</h3><p>Searches can be sent only to a provider that your server allowlist permits.</p><div class="setting-row"><div><label>Search URL template</label><small>Include {query}, e.g. your own search service.</small></div><input id="search-template" type="text" value="${escapeHtml(state.browserSearchTemplate)}" placeholder="https://search.example/?q={query}"></div><div class="setting-row"><div><label>Clear browser history</label><small>Bookmarks are left intact.</small></div><button class="setting-button" id="clear-history">Clear</button></div><div class="setting-row"><div><label>Clear bookmarks</label><small>Removes local FigureOS browser bookmarks.</small></div><button class="setting-button" id="clear-bookmarks">Clear</button></div></section>
  <section class="settings-card"><h3>System</h3><p>Install, updates, and lock-screen behavior.</p><div class="setting-row"><div><label>Lock screen</label><small>Show the FigureOS lock screen when requested.</small></div><button id="lock-toggle" class="toggle ${state.lockEnabled?'on':''}" aria-label="Toggle lock screen"></button></div><div class="setting-row"><div><label>Install FigureOS</label><small>Available when the browser exposes the PWA install prompt.</small></div><button class="setting-button primary" id="install-pwa">Install</button></div><div class="setting-row"><div><label>Check for updates</label><small>Asks the service worker to update now.</small></div><button class="setting-button" id="check-update">Check</button></div><div class="setting-row"><div><label>Lock now</label><small>Hide the current workspace behind the lock screen.</small></div><button class="setting-button" id="lock-now">Lock</button></div></section>
  <section class="settings-card wide"><h3>Proxy security</h3><p>The frontend never receives Bunny secrets or upstream credentials. The backend validates an exact origin allowlist, blocks private/loopback address resolution, rate limits requests, caps bodies and responses, strips hop-by-hop headers, keeps upstream cookies in an isolated server-side jar, and refuses upstream pages that explicitly deny framing. Configure allowed destinations in <code>PROXY_ALLOWED_ORIGINS</code>.</p></section>`;
  bindSettings();}
function bindSettings(){document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{applyTheme(b.dataset.theme);renderSettings();});document.querySelectorAll('[data-particles]').forEach(b=>b.onclick=()=>{applyParticles(b.dataset.particles);renderSettings();});document.querySelectorAll('[data-wallpaper]').forEach(b=>b.onclick=()=>{const id=b.dataset.wallpaper;if(id==='custom'&&!state.customWallpaper){document.getElementById('custom-wallpaper').focus();return;}patchState({wallpaper:id});applyWallpaper(id);renderSettings();});const custom=document.getElementById('custom-wallpaper');custom.onchange=()=>{patchState({customWallpaper:custom.value.trim(),wallpaper:custom.value.trim()?'custom':state.wallpaper});applyWallpaper();renderSettings();};document.getElementById('search-template').onchange=e=>patchState({browserSearchTemplate:e.target.value.trim()});document.getElementById('clear-history').onclick=()=>{patchState({history:[]});toast('Browser history cleared.');};document.getElementById('clear-bookmarks').onclick=()=>{patchState({bookmarks:[]});toast('Bookmarks cleared.');};document.getElementById('lock-toggle').onclick=()=>{patchState({lockEnabled:!state.lockEnabled});renderSettings();};document.getElementById('lock-now').onclick=()=>window.dispatchEvent(new CustomEvent('figureos:lock'));document.getElementById('install-pwa').onclick=async()=>{if(window.figureosInstallPrompt){window.figureosInstallPrompt.prompt();await window.figureosInstallPrompt.userChoice;window.figureosInstallPrompt=null;}else toast('Install prompt is not currently available. Use your browser’s install command if supported.');};document.getElementById('check-update').onclick=async()=>{const r=await navigator.serviceWorker?.getRegistration();if(r){await r.update();toast('Update check complete.');}else toast('Service worker is not active.');};}
function toast(message){window.dispatchEvent(new CustomEvent('figureos:toast',{detail:{title:'Settings',message}}));}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
